## Ingesting Zone Data into Postgres

In [18]:
import pandas as pd

from tqdm.auto import tqdm

In [3]:
url = 'https://github.com/DataTalksClub/nyc-tlc-data/releases/download/misc/taxi_zone_lookup.csv'

url

'https://github.com/DataTalksClub/nyc-tlc-data/releases/download/misc/taxi_zone_lookup.csv'

In [4]:
df = pd.read_csv(url)

In [5]:

df.head()

   LocationID        Borough                     Zone service_zone
0           1            EWR           Newark Airport          EWR
1           2         Queens              Jamaica Bay    Boro Zone
2           3          Bronx  Allerton/Pelham Gardens    Boro Zone
3           4      Manhattan            Alphabet City  Yellow Zone
4           5  Staten Island            Arden Heights    Boro Zone

In [6]:
from sqlalchemy import create_engine
engine = create_engine('postgresql://root:root@localhost:5432/ny_taxi')

In [7]:
print(pd.io.sql.get_schema(df, name='zones', con=engine))

CREATE TABLE zones (
	"LocationID" BIGINT,
	"Borough" TEXT,
	"Zone" TEXT,
	service_zone TEXT
)

In [ ]:
df.head(0)

Empty DataFrame
Columns: [LocationID, Borough, Zone, service_zone]
Index: []

In [9]:
df.head(n=0).to_sql(name='zones', con=engine, if_exists='replace')

0

In [13]:
dtype = {
	"LocationID": "Int64", 
	"Borough": "string", 
	"Zone": "string", 
	"service_zone": "string"
}

In [20]:
df_iter = pd.read_csv(
    url,
    dtype=dtype,
    iterator=True
)

### Iterate Over Chunks

In [ ]:
#Iterate Over Chunks

# for df_chunk in df_iter:
#     print(len(df_chunk))

265

In [21]:
for df_chunk in tqdm(df_iter):
    df_chunk.to_sql(name='zones', con=engine, if_exists='append')

0it [00:00, ?it/s]